# Generated by Django 3.1.1 on 2022-10-28 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstaff',
            name='attachment',
            field=models.FileField(blank=True, default=None, upload_to='attachments/'),
        ),
    ]
