# Generated by Django 3.1.1 on 2022-10-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_auto_20221028_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='leavereportstudent',
            name='attachment',
            field=models.FileField(blank=True, default=None, upload_to='attachment/'),
        ),
    ]
